aeternity/superhero-ui

package-lock.json, src/components/TipsList.vue
- Added mainnet contract address
- Switched sdk init to mainnet node endpoint
=> Switch to mainnet

src/components/TipsList.vue
- tipnote is the title of the listing
- public key `ak_..` is now with smaller font
=> (ui) small improvements

src/components/layout/RightSectionComponent.vue
=> hide install wallet if logged in

src/App.vue, src/components/layout/LeftSectionComponent.vue, src/utils/backend.js
=> adds comments and other backend stats

src/components/layout/HeaderComponent.vue, src/components/layout/RightSectionComponent.vue
=> hides cta buttons

src/App.vue, src/components/FiatValueComponent.vue, src/components/RetipComponent.vue, src/components/tipRecords/TipRecordComponent.vue, src/store/getters.js, src/store/index.js, src/utils/aeternity.js, src/views/CreateProfile.vue, src/views/Mission.vue, src/views/Privacy.vue, src/views/Terms.vue, src/views/TipCommentsView.vue, src/views/TipsList.vue, src/views/UserProfileView.vue
closes https://github.com/aeternity/aepp-raendom/issues/24
=> Refactor store

src/App.vue, src/components/FiatValue.vue, src/components/layout/LeftSection.vue, src/contracts/OracleServiceInterface.aes, src/store/actions.js, src/store/getters.js, src/store/index.js, src/store/mutation-types.js, src/store/mutations.js, src/utils/aeternity.js, src/utils/tippingContractUtil.js, src/views/UserProfileView.vue
=> More stats

src/App.vue, src/components/Loading.vue, src/components/Retip.vue, src/components/layout/RightSection.vue, src/components/layout/SendTip.vue, src/store/actions.js, src/store/getters.js, src/store/index.js, src/store/mutation-types.js, src/store/mutations.js, src/views/TipsList.vue
=> various loading state optimizations (part-1)

src/App.vue, src/utils/walletSearch.js
=> load wallet in parallel

src/App.vue, src/store/index.js, src/utils/util.js, src/views/TipsList.vue, src/views/UserProfileView.vue
=> only reload fully if initial

src/components/layout/RightSection.vue
- add chrome store link
- update github link
=> Update wallet links

src/components/layout/RightSection.vue
=> display install wallet section only if not LoggedIn

src/components/tipRecords/TipComment.vue, src/components/tipRecords/TipRecord.vue
=> fix profile link target

.travis.yml
Right now changes from https://github.com/davidyuk/aepp-raendom is auto deployed to https://github.com/davidyuk/temp
=> travis: Setup deployments to secret repository

.travis.yml, scripts/before-deploy.sh
closes #152 
I have tested it on Travis by special configuration: https://travis-ci.com/github/aeternity/aepp-raendom/builds/153878267#L315-L318
=> travis: Generate CNAME file

src/views/UserProfileView.vue
=> UserProfileView: Require avatar trough Webpack

src/App.vue, src/components/layout/LeftSection.vue, src/components/layout/RightSection.vue, src/styles/base.scss, src/styles/layout.scss
closes #157 
this doesn't fix the centering of the layout. There will be a consecutive PR
=> Decouple layout styling

src/App.vue, src/components/tipRecords/TipComment.vue, src/components/tipRecords/TipRecord.vue, src/store/index.js, src/utils/aggregateData.js, src/views/TipCommentsView.vue, src/views/TipsList.vue, src/views/UserProfileView.vue
=> Chain name usage

src/components/tipRecords/TipComment.vue, src/components/tipRecords/TipRecord.vue, src/styles/base.scss, src/views/TipCommentsView.vue, src/views/UserProfileView.vue
Fiat value visualization should be handled after completing issues #172, #173
=> Issue 170: Aligned styles to user profile design

src/views/TipCommentsView.vue
=> Fix comments view width

src/components/tipRecords/TipRecord.vue, src/views/UserProfileView.vue
- fix retip AE symbol duplicate
- use AeAmount component where ae value is displayed (User profile)
- (closes https://github.com/aeternity/aepp-raendom/issues/173)
=> Use ae-amount component 

src/components/tipRecords/TipRecord.vue
=> Align date/time to right

src/components/layout/Navigation.vue, src/components/layout/SendTip.vue, src/components/onboarding/steps/Step2.vue, src/components/tipRecords/TipComment.vue, src/components/tipRecords/TipRecord.vue, src/utils/backend.js, src/views/TipCommentsView.vue, src/views/TipsList.vue, src/views/UserProfileView.vue
- show user avatar dynamically (closes #184)
- have getProfileImageUrl as `static` method as well
- adjust css for displaying avatar properly
- minor fixes:
- onboarding wizzard tutorial link
- onbosarding wizzard to be only visible if no wallet
- trending leads to the main tiplistview
=> Users avatars, minor css adjustments, fixes

src/App.vue, src/components/Retip.vue, src/components/layout/SendTip.vue, src/utils/aeternity.js, src/utils/backend.js, src/utils/walletSearch.js, src/views/TipsList.vue, src/views/UserProfileView.vue
in combination with https://github.com/aeternity/tipping-community-backend/pull/64
=> Load data from cache

src/components/layout/SendTip.vue, tests/e2e/specs/home.spec.js
=> display send tip section only when user has active account

src/assets/iconDrawer.svg, src/components/ExpandBlock.vue, src/styles/_variables.scss, src/views/FAQ.vue
I will style the Tutorial page in a different PR.
=> Issue #230 Styled FAQ page

src/components/Retip.vue, src/components/tipRecords/TipComment.vue, src/components/tipRecords/TipRecord.vue, src/styles/base.scss, src/views/TipCommentsView.vue, src/views/UserProfileView.vue
fixes #250 
+ some other glitches on mobile
+ cleanup and formatting
=> Fix visual issues on mobile

.eslintrc.js, src/App.vue, src/components/AeAmount.vue, src/components/Dropdown.vue, src/components/ExpandBlock.vue, src/components/FiatValue.vue, src/components/Loading.vue, src/components/Retip.vue, src/components/layout/LeftSection.vue, src/components/layout/Navigation.vue, src/components/layout/Overview.vue, src/components/layout/RightSection.vue, src/components/layout/SendTip.vue, src/components/onboarding/steps/Step2.vue, src/components/onboarding/steps/Step5.vue, src/components/tipRecords/FormatDate.vue, src/components/tipRecords/TipComment.vue, src/components/tipRecords/TipRecord.vue, src/components/tipRecords/TipTitle.vue, src/components/tipRecords/Topic.vue, src/views/CreateProfile.vue, src/views/FAQ.vue, src/views/Privacy.vue, src/views/Terms.vue, src/views/TipCommentsView.vue, src/views/TipsList.vue, src/views/UserProfileView.vue
=> Add vue recomended linter rules

src/components/tipRecords/TipRecord.vue
=> Remove random commas

src/components/Retip.vue
related PR: https://github.com/aeternity/superhero-wallet/pull/112
=> Update deeplink domain

.env, src/App.vue, src/components/Retip.vue, src/components/layout/SendTip.vue, src/utils/backend.js, src/utils/util.js, src/views/TipCommentsView.vue, src/views/UserProfileView.vue
related pr: https://github.com/aeternity/superhero-wallet/pull/123
=> Deeplink to wallet to create a comment

.travis.yml, scripts/before-deploy.sh
so, #271 was done completely wrong
I propose to switch env variables for the specific branch in travis settings.
need to remove unused env variables after merging this PR
https://travis-ci.com/github/aeternity/aepp-raendom/settings
=> Fix missed CNAME on staging, simplify travis config

src/components/onboarding/Wizard.vue, src/components/onboarding/steps/Step2.vue, src/components/onboarding/steps/Step3.vue
=> Changed texts, fixed issue with profile link on the Onboarding Wizard

src/components/tipRecords/TipRecord.vue
=> Updated tooltip for a tip record

src/components/layout/Overview.vue
- depends on backend to be deployed
=> added claimed amount to sidebar

src/config/constants.js, src/views/UserProfileView.vue
=> Changed explorer link

src/components/layout/Overview.vue
=> Stats block is visible on wider screens

src/components/AeButton.vue, src/components/Retip.vue, src/components/layout/SendTip.vue, src/views/TipCommentsView.vue
=> Change all buttons background color when disabled

src/App.vue
=> Refresh views when url is changed

src/components/tipRecords/TipComment.vue
=> Comment date shown on firefox, comment links to Tip URL page

src/styles/base.scss, src/views/UserProfileView.vue
=> Back button spacing

src/App.vue, src/utils/util.js
Related to https://github.com/aeternity/superhero-ui/pull/303
=> Warning if browser not supported

src/components/onboarding/Wizard.vue, src/components/onboarding/steps/Step1.vue, src/components/onboarding/steps/Step2.vue, src/components/onboarding/steps/Step3.vue, src/components/onboarding/steps/Step4.vue, src/components/onboarding/steps/Step5.vue, src/views/TipsList.vue
Made the wizard appear for all users until they finish it (click the button on the last step)
Apparently I had to fix the texts as they were misleading or more confusing than helpful (and had errors).
Another bug was that the Install Icons somehow appeared on the Receive Tip step which is obviously and totally wrong.
Don't know how that passed several revisions. I'm pretty sure I missed some.
close #257 close #227
=> Wizard visual fixes and text improvments

src/components/layout/MobileNavigation.vue, src/components/layout/Navigation.vue, src/components/layout/RightSection.vue
=> Removed "trending" link from main navigation

src/components/BackButtonRibbon.vue, src/styles/base.scss, src/views/TipCommentsView.vue, src/views/UserProfileView.vue
=> Created back button to use browser history

src/components/tipRecords/TipRecord.vue, src/styles/_variables.scss, src/views/TipCommentsView.vue
=> Fix Comments view background

src/views/UserProfileView.vue
=> Fixed tip preview padding on profile page

src/assets/wizardChevron.svg
=> Change chevron color

src/components/onboarding/steps/Step1.vue, src/components/onboarding/steps/Step2.vue, src/views/CreateProfile.vue, src/views/FAQ.vue
=> Added texts, fix typos

src/components/AeInputAmount.vue, src/components/Retip.vue, src/components/layout/SendTip.vue, src/styles/base.scss
=> Fix inputs related problems

src/components/layout/FooterSection.vue, src/views/CreateProfile.vue, src/views/FAQ.vue
=> Updated forum link

src/components/TipInput.vue
=> Execute correct action upon validation

.travis.yml, src/views/Privacy.vue, src/views/Terms.vue
=> Apply changes from master back to develop branch

src/components/layout/RightSection.vue
potential fixes https://github.com/aeternity/superhero-ui/issues/356
=> potential fix for rightsection loading issue

src/components/ExpandableBlock.vue
=> Expand block component opens and closes upon title click

src/components/layout/RightSection.vue
=> Added check for a loaded currency object

src/components/TipInput.vue
=> Only one tip popup opens at a time, no overlaying texts

src/components/AeInputAmount.vue
=> Set restraints for width of amount input

src/components/TipInput.vue, src/components/tipRecords/TipRecord.vue
=> Fixed retip deeplink and Tip preview points to tip preview view

src/components/TipInput.vue
=> Clear tip form after tip

src/components/modals/MobileSendTipModal.vue, src/components/tipRecords/TipRecord.vue
=> Resolved Image preview inconsistencies

src/components/AeAmountFiat.vue, src/components/TipInput.vue, src/components/tipRecords/TipRecord.vue
* Proper vertical align of AE amounts and icon
* Use ellipsis for urls
* Make the tip control in the url preview stick to bottom
* Remove redundant tooltip
=> Fix some small visual issues

src/components/onboarding/Wizard.vue
=> Removed league string from wizard button

src/components/layout/Navigation.vue, src/components/onboarding/Wizard.vue, src/components/onboarding/steps/Step2.vue, src/components/onboarding/steps/Step5.vue, src/router.js, src/views/FAQ.vue
=> Renamed Create Profile to Install Wallet

README.md, src/views/Privacy.vue, src/views/Terms.vue
=> Replace beta.superhero.com with superhero.com

src/components/Dropdown.vue, src/components/layout/RightSection.vue
=> Fixed balance visualization in wallet section

src/components/AeInputAmount.vue, src/components/layout/MobileNavigation.vue, src/components/layout/SendTip.vue, src/styles/_variables.scss, src/views/TipCommentsView.vue
=> Show Send Tip form at any time

src/components/TipsPagination.vue
=> Load tips, if scrolled to the last tip

src/components/TipInput.vue, src/views/UserProfileView.vue
ref #392
The implementation is done without approved design.
=> Added tip user button

src/components/TipsPagination.vue
=> TipsPagination: get lastTipId properly

src/components/TipsPagination.vue
=> TipsPagination: reload onscroll when activated

src/App.vue, src/components/layout/RightSection.vue, src/components/tipRecords/TipRecord.vue, src/utils/util.js
close https://github.com/aeternity/superhero-ui/issues/297
=> Update browser list that support the extension

src/views/TipCommentsView.vue
=> Comment without installed wallet

src/components/layout/Navigation.vue
=> Add league to navigation

src/components/TipInput.vue, src/components/layout/Navigation.vue
- Added league to navigation (#448)
=> Release 0.1.1

src/App.vue, src/components/TipInput.vue, src/components/TipsPagination.vue, src/components/layout/MobileNavigation.vue, src/components/layout/Navigation.vue, src/components/layout/Overview.vue, src/components/modals/MobileSendTipModal.vue, src/components/onboarding/steps/Step5.vue, src/components/tipRecords/TipComment.vue, src/utils/i18nHelper.js, src/utils/tippingContractUtil.js, src/utils/util.js, src/views/CreateProfile.vue, src/views/Maintenance.vue, src/views/Mission.vue, src/views/Privacy.vue, src/views/Terms.vue, src/views/TipCommentsView.vue, src/views/TipsList.vue, src/views/UserProfileView.vue
Should be well tested before merge
=> Refactoring

src/App.vue, src/components/AeInputAmount.vue, src/components/Loading.vue, src/components/TipInput.vue, src/components/layout/Navigation.vue, src/components/layout/Overview.vue, src/components/layout/RightSection.vue, src/components/layout/SendTip.vue, src/components/modals/MobileSendTipModal.vue, src/components/onboarding/steps/Step2.vue, src/components/onboarding/steps/Step3.vue, src/components/onboarding/steps/Step4.vue, src/locales/en.json, src/locales/zh.json, src/utils/i18nHelper.js, src/views/CreateProfile.vue, src/views/UserProfileView.vue, tests/unit/loading.spec.js
=> Extract all language into locales

src/App.vue, src/components/layout/RightSection.vue, src/store/actions.js
=> Implemented balance update

src/components/AeButton.vue, src/components/Loading.vue, src/components/TipInput.vue, src/components/TipsPagination.vue, src/components/layout/SendTip.vue, src/views/TipCommentsView.vue, src/views/TipsList.vue, src/views/UserProfileView.vue, tests/unit/loading.spec.js
=> Add loader on send

src/components/TipsPagination.vue
=> TipsPagination: add lastTipId at reloadData

.eslintrc.js, src/App.vue, src/components/AeAmountFiat.vue, src/components/AeButton.vue, src/components/AeInputAmount.vue, src/components/TipInput.vue, src/components/TipsPagination.vue, src/components/layout/LeftSection.vue, src/components/layout/MobileNavigation.vue, src/components/layout/Navigation.vue, src/components/layout/Overview.vue, src/components/layout/RightSection.vue, src/components/layout/SendTip.vue, src/components/modals/MobileSendTipModal.vue, src/components/onboarding/steps/Step2.vue, src/components/onboarding/steps/Step3.vue, src/components/onboarding/steps/Step4.vue, src/components/onboarding/steps/Step5.vue, src/components/tipRecords/TipComment.vue, src/components/tipRecords/TipRecord.vue, src/components/tipRecords/TipTitle.vue, src/views/CreateProfile.vue, src/views/FAQ.vue, src/views/Mission.vue, src/views/Privacy.vue, src/views/SingleCommentView.vue, src/views/Terms.vue, src/views/TipCommentsView.vue, src/views/TipsList.vue, src/views/UserProfileView.vue
=> Add new linter rules

src/components/SendComment.vue, src/components/TipInput.vue, src/components/tipRecords/TipComment.vue, src/components/tipRecords/TipCommentList.vue, src/components/tipRecords/TipRecord.vue, src/locales/en.json, src/views/SingleCommentView.vue, src/views/TipCommentsView.vue
=> Create nested comments functionality

src/components/AeAmountFiat.vue, src/components/TipInput.vue
=> Display tip icon on initial load

src/components/TipsPagination.vue, src/components/tipRecords/TipComment.vue, src/components/tipRecords/TipCommentList.vue, src/views/UserProfileView.vue
=> Add userChainName into TipComment component

src/components/TipInput.vue
=> If a the user is not logged, tip/retip redirect to the wallet

src/views/SingleCommentView.vue
=> SingleCommentView: do not trim comment

src/components/layout/sendTip/SendTip.vue
=> Allow not logged users to tip through wallet from send tip section

src/components/tipRecords/TipComment.vue, src/components/tipRecords/TipRecord.vue
=> Set tip message to be ontop of the preview

src/locales/en.json, src/locales/zh.json
=> Removed url status titles until the text content is figured out

src/components/AeInputAmount.vue, src/components/layout/sendTip/SendTip.vue
=> Changed amount input step

src/components/TipInput.vue, src/components/layout/sendTip/SendTip.vue
=> Set max length for tip message fields

package-lock.json, package.json, src/components/SendComment.vue
=> Created autosizeable reply fields

src/App.vue, src/components/TipsPagination.vue, src/components/layout/RightSection.vue, src/store/actions.js, src/utils/backend.js, src/utils/util.js
=> Show maintenance page if backend is down

src/components/TipInput.vue
=> TipInput: Don't encode comment content twice

src/utils/util.js
=> Workaround for timeout issue with retrieving tips

package-lock.json, package.json, src/components/BackButtonRibbon.vue, src/main.js
=> Fix BackButtonRibbon

src/components/SuccessModal.vue, src/components/tipRecords/TipRecord.vue, src/locales/en.json, src/utils/backend.js
=> Add three dots menu

.eslintrc.js, package-lock.json, package.json, src/components/AeAmount.vue, src/components/AeInputAmount.vue, src/components/FiatValue.vue, src/components/layout/FooterSection.vue, src/components/layout/MobileNavigation.vue, src/components/layout/Page.vue, src/components/layout/SearchInput.vue, src/components/onboarding/steps/Step1.vue, src/components/onboarding/steps/Step2.vue, src/components/onboarding/steps/Step3.vue, src/components/onboarding/steps/Step4.vue, src/components/onboarding/steps/Step5.vue, src/components/tipRecords/TipRecord.vue, src/locales/en.json, src/locales/zh.json, src/utils/util.js, src/views/CreateProfile.vue, src/views/FAQ.vue, src/views/Mission.vue, src/views/Privacy.vue, src/views/Terms.vue, src/views/admin/Tracing.vue
=> Fix problems in locales, add linter rules

src/utils/aeternity.js, src/utils/util.js, src/views/Maintenance.vue
=> Created recover functionality for maintenance page

src/components/Avatar.vue, src/components/AvatarWrapper.vue, src/components/SendComment.vue, src/components/layout/sendTip/SendTip.vue, src/components/tipRecords/TipComment.vue, src/components/tipRecords/TipRecord.vue, src/views/UserProfileView.vue
=> Avatar doesnt glitch when no active user is set

src/utils/util.js, src/views/TipCommentsView.vue
The issue is an invalid json response.
This is just a partial fix to show there is an error.
=> Added a catch block if json parsing breaks

src/components/TipInput.vue
ref #562 
Checkbox Component is set with the proper background.
=> Set tip input background color

src/components/layout/SearchInput.vue
=> Added rounding to the side search

src/components/ThreeDotsMenu.vue
=> Added white color on hover

src/views/TipsList.vue
=> Added margin-bottom and set sticky positioning for send tip

src/styles/base.scss
=> Removed box shadow of buttons

src/components/AeButton.vue
=> Added opacity for disabled form  buttons

src/components/layout/Navigation.vue, src/router.js, src/views/League.vue
temporary will integrate a static site until iframe issue with wordpress is resolved
=> Integrate league site as iframe

src/components/SendComment.vue, src/components/layout/sendTip/SendTip.vue, src/styles/base.scss
=> Added left caret for message inputs

package-lock.json, package.json
Due to AEX2 connectivity problems and browser detection
=> Rollback to SDK 7.1.1

scripts/before-deploy.sh, src/components/TipInput.vue, src/router.js, tests/e2e/specs/singletipview.spec.js
- it should make enabling of SSR easier in future
- consistent with a way is wallet deployed
- URLs without anchor considered as [looking more beautiful](https://router.vuejs.org/guide/essentials/history-mode.html)
=> Enable HTML5 history mode

src/views/League.vue
=> Update League iframe src with the real site

src/components/TipInput.vue
=> TipInput: Fix width issue

src/App.vue, src/components/layout/FooterSection.vue, src/components/layout/Page.vue, src/components/layout/SearchInput.vue, src/locales/en.json, src/locales/zh.json, src/store/index.js, src/views/TipsList.vue
=> Login with web-wallet on every page

src/components/tipRecords/TipRecord.vue
=> External links with no preview are opened in a new tab

src/views/UserProfile.vue
=> Fixed misplaced tip button in user profile on mobile

src/components/layout/FooterSection.vue, vue.config.js
fixes #551 
We must come to an agreement on design.
=> Add version and commit hash to a footer

src/components/TipInput.vue
=> TipInput: Fix condition to use deeplinks

src/components/TipInput.vue, src/components/tipRecords/TipRecord.vue, src/views/League.vue, src/views/UserProfile.vue
Handle some visual edge cases
Also handle 404 from backend of user profiles
=> Small css fixes

src/views/UserProfile.vue
=> Check for profile creation date

src/views/UserProfile.vue
=> Fix edit profile when biography is null

package-lock.json, package.json
- Remove inverted colors filter (#639)
=> Release 0.1.10

package.json
https://github.com/aeternity/superhero-wallet/pull/346
=> Don't lint styles in dist folder

src/components/tipRecords/FormatDate.vue
=> FormatDate: Fix date related issues

src/components/layout/RightSection.vue
=> RightSection: Exclude test tag

src/locales/en.json
*did not touch LEGAL TERMS. (waiting for legal team)
*still a lot of text to fit in but no space in current site map to put it in. Will discuss with you.
=> Text updates

package-lock.json, src/locales/en.json, src/router.js, src/views/tutorial/Meet.vue, src/views/tutorial/Voting.vue, src/views/tutorial/Wallet.vue, src/views/tutorial/Widget.vue
Added tutorial views
- Widget 
- Voting 
- Wallet
- Meet
Should be filled with text by the comms.
Also these new pages will only be linked from the FAQ and Tutorial pages, so they do not need to have a separate link in the menu or anywhere in the UI.
cc @thescientress
=> New explainer views

src/components/tipRecords/TipRecord.vue
=> Fixed shrinked tip value

src/locales/en.json
Removed tutorial for wallet, to be moved to its own FAQ/tutorial page
Minor proofread edits
=> Text updates, Moved tutorial for wallet to own page

src/views/TipsList.vue
=> Hide wizard

src/views/TipsList.vue
=> Sticky position has 1px off the top

src/components/TipsPagination.vue
I'm not sure that I have tested it enough carefully
SImilar PR: https://github.com/aeternity/aepp-base/pull/1400
=> TipsPagination: Simplify infinite loading

src/components/layout/Navigation.vue, src/router.js
- League - `/events` -> `/league`
- Meet - `/league` -> `/meet`
=> Router names update

src/store/mutations.js, src/utils/aeternity.js
ref https://github.com/aeternity/superhero-wallet/pull/418
ref #434
ref https://github.com/aeternity/aepp-sdk-js/pull/1056
=> Add on Aepp disconnect event

src/App.vue, src/components/ListOfTipsAndComments.vue, src/components/TipsPagination.vue, src/components/layout/Navigation.vue, src/components/layout/SearchInput.vue, src/components/tipRecords/Topic.vue, src/router.js, src/store/index.js, src/store/modules/backend.js, src/store/mutations.js, src/utils/backend.js, src/views/SingleComment.vue, src/views/TipComments.vue, src/views/TipsList.vue
closes #664 
depends on #691, #702
=> Avoid wrapping of RouterView with KeepAlive

src/App.vue, src/components/tipRecords/TipRecord.vue, src/store/index.js, src/utils/backend.js, src/utils/backendAuthMixin.js, src/views/TipComments.vue, src/views/UserProfile.vue
Rebased and refactored version of #709 
As I think, this is a more easily reusable version of the conditional calling of web wallet and extension
closes #701
=> Set pinning and reporting to work with web-wallet

src/views/Conference.vue
Fix the bug at meet page.
New conference was not inited by the Vue prop change.
=> Hotfix meet bug

src/components/layout/sendTip/SendTip.vue
it was broken in 4b5a2dd03b3e3397d3f9283e00e5175af66839fd
=> SendTip: Fix icon size

src/views/Conference.vue
issue https://github.com/aeternity/superhero-ui/issues/728
=> Dispose jitsi instance

src/assets/backArrow.svg, src/components/Avatar.vue, src/components/MessageInput.vue, src/components/SendComment.vue, src/components/layout/sendTip/SendTip.vue, src/components/layout/sendTip/UrlStatus.vue, src/components/tipRecords/TipCommentList.vue, src/components/tipRecords/TipRecord.vue, src/styles/_mixins.scss, src/styles/base.scss, src/utils/util.js, src/views/TipComments.vue, src/views/UserProfile.vue
=> Extract MessageInput component

src/views/UserProfile.vue
=> UserProfile: Update data on address change

src/router.js
the second commit implements a workaround for #690
=> Remove useless navigation guards and initial 404 behaviour

src/views/TipsList.vue
It was duplicated in #748
https://github.com/aeternity/superhero-ui/commit/c5d2f722caf7cf8219148c64f209c55830f224af#diff-d99b2ab58bd091cea571502b1e3e8047L38-R48
closes #758
=> TipsList: Remove duplicate TipsPagination

src/components/tipRecords/TipRecord.vue, src/utils/util.js
=> TipRecord: Show claim button only if address available

src/components/Avatar.vue, src/components/ButtonPlain.vue, src/components/Link.vue, src/components/OutlinedButton.vue, src/components/layout/FooterSection.vue, src/router.js
=> Fix errors, warning on init load

src/components/ButtonPlain.vue, src/components/Link.vue
=> Change prop type in Link component

src/utils/backend.js
Issue was the correct headers were not passed when an image is uploaded
fixes #773
=> Fix image upload request

.eslintrc.js, src/components/layout/FooterSection.vue, src/components/tipRecords/AuthorAndDate.vue, src/views/CreateProfile.vue, src/views/FAQ.vue, src/views/Mission.vue, src/views/Privacy.vue, src/views/Terms.vue, src/views/tutorial/Meet.vue, src/views/tutorial/Voting.vue, src/views/tutorial/Wallet.vue, src/views/tutorial/Widget.vue
=> eslint: Force PascalCase for components registered globally

src/views/Maintenance.vue
I propose this solution to fix #725.
=> Maintenance.vue: Remove fixed position to allow scroll on iPhone 6/7/8

src/App.vue, src/store/modules/backend.js
I propose this fixes for errors hell when you can't fetch data from backend (for example, when you have #363 issue). And I don't fix fetch error, because it's primary reason for other errors.
=> Fix maintenance errors

src/locales/es.json
Translation done by Manel Ruiz and reviewed by Alex Casas, based on original English source file on https://github.com/aeternity/superhero-ui/blob/develop/src/locales/en.json
=> Spanish translation

src/components/tipRecords/TipRecord.vue, src/locales/en.json
#783 should be merged first
fixes #764 (made it more user friendly)
fixes #633 
depends on #781
=> Fix claim button

src/views/TipsAndComments.vue, src/views/TipsList.vue, src/views/UserProfile.vue
fixes #794 ,
fixes #792,
fixes #787,
This PR also fixes problem of not showing the 0 comments etc. in the userProfile
=> Fix ui issues

src/components/tipRecords/TipRecord.vue
Fixes #765 
Displaying tip amount even if no preview is available
=> Tip amount display for tips with no preview generated

src/components/layout/Navigation.vue
Fixes #800 
This also reveals the `Meet` option in the navigation section. Merge only when confirmed it works properly and has to be included.
=> Navigation reordering

.eslintrc.js, src/views/CreateProfile.vue, src/views/FAQ.vue, src/views/Mission.vue, src/views/Privacy.vue, src/views/Terms.vue, src/views/tutorial/Meet.vue, src/views/tutorial/Voting.vue, src/views/tutorial/Wallet.vue, src/views/tutorial/Widget.vue
=> Fix FAQ collapse sections

src/components/Modal.vue
Seems to fix #808. Needs testing.
=> Lower z-index on three dot menu

src/utils/aeternity.js
it looks like a typo that I have introduced in #721 
is it intended to be used somehow?
=> Disable wallet in hidden iframe on mobile

src/components/SendComment.vue, src/utils/util.js
=> SendComment: catch an error while sending

src/components/layout/SearchInput.vue
closes #826 
https://lodash.com/docs/4.17.15#debounce
https://css-tricks.com/debouncing-throttling-explained-examples/
=> SearchInput: Debounce requests

src/components/FilterButton.vue, src/components/ListOfTipsAndComments.vue, src/components/ThreeDotsMenu.vue, src/components/tipRecords/AuthorAndDate.vue, src/views/UserProfile.vue
Fixes design inconsistencies  described in issues #823  #824
=> User profile design adjustments

package-lock.json, src/components/AeInputAmount.vue, src/components/layout/RightSectionWallet.vue, src/config/constants.js, src/utils/aeternity.js
still waiting for backend changes to be testable
=> fungible token featureflagged via existence of v2 contract

.env, .env.e2e, package.json, src/config/constants.js, src/utils/aeternity.js, src/utils/backend.js, src/views/UserProfile.vue
https://cli.vuejs.org/guide/mode-and-env.html#modes
This is more flexible and consistent than the current approach.
=> Use vue-cli to switch prod and test configs

src/components/TipInput.vue
The original error was:
> TypeError: Cannot read property 'total_amount_ae' of null
at a.isTokenAndZeroAeTip
=> TipInput: Fix warnings

src/router.js
depends on https://github.com/aeternity/jitsi-meet/pull/262
=> Redirect to meet on mobile

package-lock.json, package.json, vue.config.js
This was the first version based on iframes, I don't think that somebody still uses it.
=> Drop superhero-button@0.1.* support

src/components/tipRecords/TipComment.vue
@davidyuk as you mentioned after [this conversation](https://github.com/aeternity/superhero-ui/issues/833) I just remove cursor from comment page.
=> Don't show cursor at comment page

src/components/MessageInput.vue, src/components/PlayButton.vue, src/components/SendComment.vue
=> Refactor MessageInput and SendComment

src/components/layout/sendTip/SendTip.vue
Fixes duplicate form submission in Firefox. https://youtu.be/uYNLUh2rDI4
=> SendTip: Remove extra submit handler

src/components/Dropdown.vue
fixes https://github.com/aeternity/superhero-wallet/issues/660
=> Dropdown: Remove data wrapper around prop

vue.config.js
Previous background and theme colors were taken from base-aepp, i am proposing to change, so they match current design.
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/9008074/101446867-d2757c00-396f-11eb-8550-1704c9b0efdc.png)|![image](https://user-images.githubusercontent.com/9008074/101446886-d903f380-396f-11eb-9c4a-e61547cc875a.png)|
=> Change background and theme colors

vue.config.js
Generated Firefox app icon
Before 😆  | After
---|---
=> Update favicon config

src/components/TipInput.vue
=> Fixed visualization of tip input on User profile page

src/components/layout/Navigation.vue, src/locales/en.json, src/views/FeedList.vue
introduced in 0f571468549d82e4800881feb567c8cb79953757
=> Fix wording related warnings

src/components/tipRecords/TipMedia.vue
Fixes #931
Grid is used to achieve the same look, but the markup  is shorter and more readable now.
=> Used grid to simplify TipMedia component

src/components/CookiesDialog.vue, src/components/UserInfo.vue, src/store/modules/backend.js, src/utils/backend.js
=> Extract setCookies action into backend

src/components/layout/SearchInput.vue
=> SearchInput: Drop v-model

src/components/FeedPagination.vue, src/components/Loader.vue, src/components/Loading.vue
Upon merging this PR in develop, the new loader could be applied to wordbazaar project. 
@thepiwo Could you please review the PR? Not sure why I can't add you as a reviewer.
=> Created a new loader indicator

.env, src/App.vue, src/components/TipInput.vue, src/components/UserInfo.vue, src/components/layout/MobileNavigation.vue, src/components/layout/sendTip/SendPost.vue, src/components/layout/sendTip/SendTip.vue, src/store/index.js, src/store/modules/aeternity.js, src/store/modules/backend.js, src/store/mutations.js, src/utils/backendAuthMixin.js
Refactoring the project. Move all possible Aeternity utils to the store by the Vuex module.
Hello @Liubov-crypto 
Please test:
- tippting (with extension and web wallet)
- retip (with extension and web wallet)
- comment (with extension and web wallet)
- it is shows right account balance (with extension)
--------------
close #909
=> Feature/aeternity to store (refactoring for the SSR)

src/components/WordBuySellButtons.vue, src/components/WordListing.vue, src/locales/en.json, src/views/WordBazaar.vue, src/views/WordDetail.vue
=> WordBazaar No Raw Text and Page Titles

src/components/AeButton.vue, src/components/AlertModal.vue, src/components/CreateToken.vue, src/components/WordBuySellButtons.vue, src/locales/en.json, src/views/WordDetail.vue
Closes #955 
Closes #956 
Closes #957 
Closes #966
=> Word Bazaar Error Handling

src/App.vue
=> App: Fix issue with updating cookies consent

src/components/FeedPagination.vue, src/components/Loader.vue
=> Loader: Do not use classes as properties

src/components/FiatValue.vue
| Before | After |
| - | - |
| ![ezgif-1-21b05560c298](https://user-images.githubusercontent.com/13139371/105370485-4d3ae380-5c0c-11eb-9ceb-5f5978ebbede.gif) | ![ezgif-1-750ef423ca0a](https://user-images.githubusercontent.com/13139371/105370498-4f9d3d80-5c0c-11eb-8b82-6d296bb4475f.gif) |
=> Fix: fiat value 0 instead of NaN

src/components/AlertModal.vue, src/components/CreateToken.vue, src/components/VoteCard.vue, src/components/WordBuySellButtons.vue, src/locales/en.json, src/store/index.js, src/styles/_mixins.scss, src/utils/backend.js, src/views/WordBazaar.vue, src/views/WordDetail.vue
Closes #978 
Closes #979 
Closes #989 
Closes #990
Step-loader is shown when you buy/sell tokens.
You can add messages, to explain why the vote is initiated.
Search functionality for assets.
Loading indicator while the list of assets is fetched.
=> WordBazaar - Design adjustments and Search

package-lock.json, package.json, src/components/layout/sendTip/SendTip.vue, src/utils/index.js
=> Normalize URL before validation

src/components/WordListing.vue, src/components/layout/RightSectionWallet.vue, src/locales/en.json, src/locales/es.json, src/locales/fr.json, src/locales/zh.json, src/styles/_variables.scss, src/utils/backend.js, src/views/WordBazaar.vue
Closes #1004 
-Switch token info on right side
- Reduced wording related warnings
- Buy/Sell price in listing
=> WordBazaar - Switch token info on right side, Buy/Sell price in listing

src/App.vue, src/components/WordBuySellButtons.vue, src/components/layout/RightSectionWallet.vue, src/store/index.js, src/store/mutations.js
Compare 'word' with wordRegistry instead with tokenInfo
=> WordBazaar - Fix word-dropdown, not triggering, message not changing on sell

package.json, src/components/tipRecords/TipRecord.vue
depends on backend https://github.com/aeternity/tipping-community-backend/pull/271 but not breaking as post without tip are not used yet
=> update tip type

package.json, src/components/tipRecords/TipRecord.vue, src/store/index.js, src/store/mutations.js, src/utils/middleware.js
=> Middleware access with swagger

src/components/Avatar.vue, src/components/UserInfo.vue, src/utils/backend.js
In preparation for the https://github.com/aeternity/tipping-community-backend/pull/277 which will be deployed in 1.9.0
=> fix: adjusts some backend requests to comply with stricter standards

src/components/AeInputAmount.vue, src/components/CreateToken.vue, src/components/PriceHistory.vue, src/components/VoteCard.vue, src/components/WordBuySellButtons.vue, src/components/WordListing.vue, src/locales/en.json, src/locales/es.json, src/locales/fr.json, src/locales/zh.json, src/views/WordBazaar.vue, src/views/WordDetail.vue
Closes #1032 
- Removed abbreviation
- Name limited to 14 symbols and a copy passed as a ticker when creating
- Some design adjustments to fit
=> WordBazaar drop abbreviation

src/App.vue, src/components/layout/FooterSection.vue, src/components/layout/Navigation.vue, src/components/layout/RightSectionTitle.vue, src/components/layout/RightSectionTopics.vue, src/components/layout/RightSectionWallet.vue, src/components/layout/sendTip/SendPost.vue, src/components/tipRecords/TipRecord.vue, src/views/FeedList.vue
- "My Profile" position in navigation changed to 2nd
- When on "Feed" -> "Main" the option is "Create post" instead of "Send Tip"
- Not working buttons (functionality not yet implemented) hidden in "Create Post" and "Tip Record"
- Iframe wallet height adjusted to fit with the re-design
=> Minor design adjustments

src/store/index.js
To fix showing of trending section.
=> Handle exception on getting word registry at an old version of backend

src/store/modules/aeternity.js
Added missing Crypto import, which caused Post without fix with zero balance to break.
Fixes #1078
=> Added missing Crypto import

src/views/TipsAndComments.vue
Meta tags are added to ``head`` section.
What is the current SSR state so the social media previews can be generated?
=> Meta tags for social media previews

src/components/Dropdown.vue, src/views/Conference.vue
=> Do not display scrollbars in dropdowns - Firefox

src/App.vue, src/components/layout/RightSectionWallet.vue, src/store/index.js, src/store/modules/aeternity.js, src/store/mutations.js
can be tested with https://github.com/aeternity/superhero-wallet/pull/1043
=> Enable account switching

src/locales/en.json, src/locales/es.json, src/locales/fr.json, src/locales/zh.json, src/views/WordBazaar.vue, src/views/WordBazaarAssets.vue, src/views/WordBazaarCreateToken.vue, src/views/WordBazaarGetAe.vue, src/views/WordBazaarHowItWorks.vue
=> Remove URLS and numbers from wording

src/components/VoteCard.vue
=> Remove prop mutation

src/components/tipRecords/TipRecord.vue
=> Hide claim option for posts without tips

.env.tnet, src/store/index.js
URL provided by Keno, fixes #1107
=> chore: fix testnet URL

src/views/WordDetail.vue
can't test WB because of broken testnet, needs to be tested properly
=> refactor: load WordInfo async

src/App.vue, src/assets/iconDrawer.svg, src/components/ExpandableBlock.vue, src/components/TopicList.vue, src/components/layout/MobileNavigation.vue, src/components/layout/Navigation.vue, src/components/layout/RightSectionTopics.vue, src/components/layout/SearchFeed.vue, src/components/tipRecords/Author.vue, src/components/tipRecords/AuthorAndDate.vue, src/components/tipRecords/Topic.vue, src/router.js, src/store/index.js, src/store/modules/backend.js, src/store/mutations.js, src/styles/base.scss, src/views/FeedList.vue, src/views/Landing.vue, src/views/TipsAndComments.vue, src/views/WordDetail.vue, tests/e2e/specs/home.spec.js
Need to ensure:
- that field looks correct in different modes
- Author popup looks fine
=> Preparations to SSR

.eslintrc.js, src/components/AeAmount.vue, src/components/CookiesDialog.vue, src/components/FiatValue.vue, src/components/ThreeDotsMenu.vue, src/components/UserInfo.vue, src/components/fungibleTokens/TokenAvatarAndSymbol.vue, src/components/layout/FooterSection.vue, src/components/layout/MobileNavigation.vue, src/components/tipRecords/TipPreview.vue, src/views/Landing.vue, src/views/WordBazaarCreateToken.vue, src/views/WordBazaarGetAe.vue, src/views/admin/Tracing.vue
with the same reasoning as in https://github.com/aeternity/superhero-wallet/pull/918
=> refactor: disable vue-i18n/no-raw-text rule

src/locales/en.json, src/locales/es.json, src/locales/fr.json, src/locales/zh.json
=> refactor: remove unused wording

src/components/FeedItemMenu.vue, src/locales/en.json
=> refactor(wording): update claim wording

src/components/UserInfo.vue
=> fix(user-info): add initial profile, include loading stage

.circleci/config.yml
Sample and temporal circleci config to avoid PR checks.
=> ci(circleci-build): initial circleci config to avoid failed PR checks

public/index.html
This PR is supported by the Æternity Crypto Foundation
=> fix: strong tag in index.html
