src/components/Dropdown.vue, src/components/Retip.vue, src/components/layout/LeftSection.vue, src/components/layout/RightSection.vue, src/components/layout/SendTip.vue, src/components/tipRecords/TipComment.vue, src/components/tipRecords/TipRecord.vue, src/components/tipRecords/TipTitle.vue, src/components/tipRecords/Topic.vue, src/styles/_mixins.scss, src/styles/_variables.scss, src/styles/base.scss, src/views/CreateProfile.vue, src/views/Mission.vue, src/views/Privacy.vue, src/views/Terms.vue, src/views/TipCommentsView.vue, src/views/TipsList.vue, src/views/UserProfileView.vue, vue.config.js
closes #147 
Proposal after research is to use sass-loader automatically include variables and mixins, which are required by components.
Including of `base.scss` everywhere results in adding the behemot bootstrap framework for each of the tens components
=> Remove duplication of style definitions

src/components/tipRecords/TipRecord.vue, src/views/TipCommentsView.vue
fix #189 
Note: styling this case is not really universal. I had to hack it.
Can't test it on Safari desktop.
also fixed a buggy scroll when you click on ❤ in profile-view -> tips
Also note: this is not for all images only for tip previews! Similar could be done for avatars for instance though there might need adjustments.
=> Hide browser's broken-image icon/border

src/components/tipRecords/TipRecord.vue
Fix: some tips without images, but with valid description and title not being visualized.
- update isPreviewToBeVisualized check
=> Fix: some tips w/o images not visualized

src/components/tipRecords/TipRecord.vue, src/styles/_variables.scss
It appears that background colors were off a little. Fixed according the design - in the design files was used opacity 50% which was misleading when picking the color values, so had to adjust
=> Fix preview background colors

src/App.vue, src/components/layout/Navigation.vue
Please check for misbehavior
Since it is kind of hackish I will describe a little:
First trick I used is to use `keep-alive` for views (we don't have much of these, so I guess no big resource waste, tough I put a reasonable limit there. This will keep the page size and allows to use scrollTo (else we would have unreachable positions until all desired pages are loaded). Also speeds up the interface as a bonus.
Scroll position is saved when clicked (in fact I had to use mousedown) somewhere (unfortunately any other vue events always return 0 for scroll positions, i guess because `window` is not yet updated with scroll data). 
When you navigate to any url, scroll will be restored if has been visited. What we actually try to achieve. Tough there is a side-effect: Restore position happens on …
=> Restore Scroll position when navigated back

src/components/TipInput.vue
Deep Links are set as per this documentation:
https://github.com/aeternity/superhero-wallet/blob/932e1b6926699174bd1583f5247163ca09bef4f8/tests/pages/index.html
The issue with empty url field when "tip" action is executed, still persists.
ref #437
=> Deeplink for Tip action on mobile

public/index.html, src/components/tipRecords/TipRecord.vue
Removed embedly because of leagal reasons for cookies and tracking when embedding youtube content.
Also design for different types of rich content should be placed before that.
=> Remove embedly integration

src/utils/util.js
The problem is that a comment like "test comment" becomes "test%20comment" after creation.
As I understand, this happens because firstly `encodeURIComponent` transforms "test comment" into "test%20comment" and then `searchParams.set` assumes that payload is not encoded and transforms "test%20comment" into "test%2520comment". So, I guess that it is not necessary to call `encodeURIComponent` before passing a value into `searchParams.set`.
=> util: Don't encode comment content twice

src/components/AeAmount.vue, src/components/AeAmountFiat.vue, src/components/TipInput.vue, src/components/layout/Overview.vue, src/components/layout/RightSection.vue, src/components/tipRecords/TipRecord.vue, src/views/UserProfileView.vue
close #511 
In case someone is interested: It appears that `flex: 0` is misinterpreted as `0 0 0%` instead of expected `0 0 auto` which makes the icon behave weirdly (probably because dimensions are also implicitly set), so apparently `flex:` should be used with its full syntax (despite it is essentially a shortcut).
Also improved the consistency for alignment of amounts and icons (and cleaned up some leftovers from refactoring fiat component)
=> Improve consistency of tip icons

src/components/layout/FooterSection.vue
Please review the footer behaviour on bigger resolutions - 1280px+ screens. An adjustment may be needed.
=> Footer is not trimmed on smaller screens

src/utils/util.js
@petbaik send me the error report:
```
{
"id":25,
"appVersion":"0.0.26",
"browser":"{\"name\":\"chrome\",\"version\":\"81.0.4044\",\"os\":\"Windows 10\"}",
"error":"{\"message\":\"Could not find parent comment with id null\",\"type\":\"vue-error\",\"payload\":{\"id\":1226,\"text\":\"Thank you for your support and checking out my music!\"},\"info\":\"v-on handler (Promise/async)\"}",
"platform":"web",
"description":"Could not comment under a post!",
"time":"1589902211663.0",
"createdAt":"2020-05-19 15:30:34.629 +00:00",
"updatedAt":"2020-05-19 15:30:34.629 +00:00"
}
```
The problem is when the user tries to create a root comment, superhero-ui redirects him via deeplink with `parentId=undefined` that the wallet trying to parse as a number. It completely breaks commenting in that case.
=> createDeepLinkUrl: Omit undefined and null values

src/App.vue
fixes #648 
In case we don't have extension or we don't init it with seed phrase the `created` of an App.vue got stucked on `initialLoad` method, because it is frozen on scanning for the wallet till it find it. I propose to subscribe for the events first (before initialLoad).
=> App: Subscribe on events before initialLoad

src/components/tipRecords/TipRecord.vue
from the discussion in #345 looks like that it depends on #708 
I have not tested this change carefully, but I think we should get rid of this
=> TipRecord: Avoid extra rerendering

src/App.vue, src/components/Avatar.vue, src/components/ListOfTipsAndComments.vue, src/components/MessageInput.vue, src/components/TipInput.vue, src/components/layout/Navigation.vue, src/components/layout/RightSectionWallet.vue, src/components/layout/sendTip/SendTip.vue, src/components/tipRecords/TipRecord.vue, src/store/index.js, src/store/mutations.js, src/utils/backendAuthMixin.js, src/views/UserProfile.vue
I think this naming is more consistent with other projects. I propose to assume account an object with `address`, `balance`, `name`, and other keys like them.
=> Rename state.account to state.address

src/components/layout/sendTip/SendTip.vue, src/utils/util.js
Fixes #780 
Extended requests timeout and after sending tip the reloading is delayed, to ensure enough time the back-end to process it.
=> Extended timeout

src/components/SendComment.vue
It can be super annoying to type it again if I'm trying to send it in a different way/to make one more attempt
#822
=> SendComment: Preserve comment if it wasn't being sent

src/components/__tests__/Loading.js, src/utils/aeternity.js, vue.config.js
Pros to do that:
- remove one way to write inconsistent (until it is not enforced by linter)
- `@` imports is not a standard, if somebody would like to import our code he has to set up our's imports parsing by himself
Cons:
- in some cases imports is longer (I think is not a big deal if the project is good enough structured)
=> vue cli: Drop @ alias

src/components/layout/FooterSection.vue, src/components/layout/RightSectionWallet.vue, src/store/mutations.js, src/utils/aeternity.js
original issue: on #810 web wallet sometimes is opening even if the extension is installed
The increasing of timeout helps in that case, so probably app initialization takes a bit longer on that branch. But initialization time also depends on the hardware and network conditions so, as in https://github.com/aeternity/superhero-wallet/pull/540, I'm proposing to don't depend on timeouts.
In particular, I think we should increase the timeout so some upper bound (10 seconds instead of 2?) and to allow the user to open the web wallet manually if he wants to use it. Until we find a way to use the extension and the web wallet simultaneously (https://github.com/aeternity/superhero-ui/issues/606).
=> Increase iframe wallet timeout, add a button to enable it manually

src/components/tipRecords/TipRecord.vue, src/components/tipRecords/TipTitle.vue, src/components/tipRecords/Topic.vue
I'm proposing to use the same styles to show topics in Tips and in the sidebar:
Also, fixes in Topic component enables more accurate rendering:
| Before | After |
|---|---|
| <img width="366" alt="Screenshot 2020-10-15 at 07 55 43" src="https://user-images.githubusercontent.com/9007851/96078963-4e959b00-0ebc-11eb-8057-42b6c3d59ea4.png"> | <img width="366" alt="Screenshot 2020-10-15 at 07 55 29" src="https://user-images.githubusercontent.com/9007851/96078968-4fc6c800-0ebc-11eb-87a8-3b7f95ad0858.png"> |
=> Refactor TipTitle component

src/components/tipRecords/AuthorAndDate.vue
Well, the goal to achieve a delay in user card showing using pure css is achievable, but the resulting UI is quite poor. I'm fixing two annoying things that were introduced in #814 because of my guidance.
| Case | Before | After |
|---|---|---|
| Accidental hovering on avatar placing the cursor on the place of card afterward | ![bug-1-before](https://user-images.githubusercontent.com/9007851/98166655-d4739780-1ef8-11eb-9768-057cb687783d.gif) | ![bug-1-after](https://user-images.githubusercontent.com/9007851/98166666-d63d5b00-1ef8-11eb-827d-9ce9d58a70ab.gif) |
| Multiple hovering on avatar before the card gets hidden | ![bug-2-before](https://user-images.githubusercontent.com/9007851/98166670-d89fb500-1ef8-11eb-9233-32b7ca3112e2.gif) | …
=> Fix UI issues of UserCard

src/App.vue, src/components/SendComment.vue, src/main.js, src/store/index.js, src/store/modules/backend.js, src/store/mutations.js, src/utils/aeternity.js, src/utils/backend.js, src/utils/backendAuthMixin.js, src/utils/index.js, src/views/Maintenance.vue, src/views/TipsAndComments.vue
=> Don't use event bus in several cases

package-lock.json, package.json, src/App.vue, src/locales/en.json, src/locales/es.json, src/locales/fr.json, src/locales/zh.json, src/utils/index.js
This warning looks outdated for instance in Safari because the web version of the wallet works fine there.
=> Drop is supported browser check because of web version of wallet

src/components/tipRecords/TipPreview.vue
Fixes #885 
If the preview is not generated yet the proper "No preview available" view is shown
Before:
After:
=> Missing preview fix

src/assets/iconVenture.svg, src/components/layout/FooterSection.vue
While #894 I have noticed that that logo's font is broken. According to SVG, the font should be Roboto, 11px. It is the same as the near text, so I assumed that is should be fine to extract "Branded by Venture" as text ant to put it near their logo.
Before:
After:
=> Extract text from Venture logo

src/components/TipInput.vue, src/router.js
closes #896 
https://router.vuejs.org/guide/essentials/redirect-and-alias.html
https://router.vuejs.org/api/#router-resolve
> This is a good proposition but we should have in mind the existing profile tips which point to /user-profile/...
I think this is fine to add a fallback redirect
=> Change path of user page, add fallback redirect

.github/workflows/main.yml
https://github.com/aeternity/superhero-wallet/pull/780
> On February 15th, GitHub Actions will remove support for referencing actions using the shortened version of a git commit SHA. This may cause some workflows in your repository to break. To fix these workflows, you will need to update the action reference to use the full commit SHA.
=> ci: don't use deprecated short sha

src/components/TipInput.vue
Fixes
```
Error in render: "TypeError: Cannot read property 'amount' of null"
found in
---> <TipInput> at 
```
=> TipInput: Check lagestTipAmount for null

src/components/layout/RightSectionWallet.vue
Fixes #1089
<div style="display:flex">
--->
</div>
=> Adjust half-closed wallet height

src/components/AeAmountFiat.vue
Before:
In debugger:
After:
somehow it works correctly in the latest release 🤔
=> fix(AeAmountFiat): remove extra space between ae and fiat

src/components/AlertModal.vue, src/components/CookiesDialog.vue, src/components/tipRecords/AuthorAndDate.vue, src/components/tipRecords/SoundCloudEmbed.vue, src/components/tipRecords/SoundCloudPlayer.vue, src/components/tipRecords/TipMedia.vue, src/components/tipRecords/TipPreview.vue, src/components/tipRecords/TipPreviewImage.vue, src/components/tipRecords/TipRecord.vue, src/components/tipRecords/TipTitle.vue, src/components/tipRecords/TipUrlDetails.vue, src/components/tipRecords/TwitterEmbed.vue, src/components/tipRecords/YouTubeEmbed.vue
Approach from #1129 applied to TipRecord based on #1135
The only significant change is that the preview always points to a link that this preview for instead of a link to tip comments. This looks reasonable and was easier to implement. @onvisions is it acceptable?
@Liubov-crypto ensure that all kinds of tips behave the same as before except for the issue mentioned above.
=> refactor(TipRecord): use plain link

src/components/AeInputAmount.vue
=> fix(AeInputAmount): show correct fiat value

src/components/FeedItemMenu.vue, src/components/SendComment.vue, src/components/TipInputPopup.vue, src/components/UserInfo.vue, src/components/layout/sendTip/GiphySearch.vue, src/components/layout/sendTip/SendPost.vue, src/components/layout/sendTip/SendTip.vue, src/store/index.js, src/store/modules/aeternity.js, src/store/modules/backend.js, src/utils/backend.js, src/utils/index.js, src/views/TipsAndComments.vue
Known exceptions:
```
[Vue warn]: Error in mounted hook (Promise/async): "Error: Request failed with 400"
found in
---> <WordDetail> at src/views/WordDetail.vue
<App> at src/App.vue
<Root>
```
when opening details of word with a space in the name (https://github.com/aeternity/tipping-community-backend/issues/368)
---
```
GET https://testnet.superhero.aeternity.art/profile/image/ak_2UGL6qArnbWx9fEkJyszssMkCjpu3VeLFBPA6MXYV3APfDSz1k 404
```
Chrome always report 404 even if they handled, we can't avoid it
---
I'm proposing a way how errors should be handled:
- don't throw an error if it is somehow indicated in ui (red color or a separate modal window)
- if an error indicated somehow, it may be printed to console (to be able to debug it in production)
Later all not caught exceptions will show …
=> refactor(backend): throw exception instead of returning null
